from tkinter import *
import pygame
pygame.init()
pygame.mixer.music.load('Audio/music.mp3')
pygame.mixer.music.play()
janela = Tk()
janela.title('Quiz Of Tecnology 1.0')
janela.geometry('1200x630')
janela.configure(background='black')
font = ('Arial', '20', 'bold')

#   IMAGENS:

image1 = PhotoImage(file="Imagens/bg.gif")
image1 = image1.subsample(1, 1)
labelimage = Label(bg='black', image=image1)
labelimage.place(x=5, y=5, relwidth=1.0, relheight=1.0)

image2 = PhotoImage(file="Imagens/comojogar.gif")
image2 = image2.subsample(1, 1)
labelimage2 = Label(bg='black', image=image2)

image3 = PhotoImage(file="Imagens/image1.gif")  # 1
image3 = image3.subsample(1, 1)
labelimage3 = Label(bg='black', image=image3)

image4 = PhotoImage(file="Imagens/image2.gif")  # 2
image4 = image4.subsample(1, 1)
labelimage4 = Label(bg='black', image=image4)

image5 = PhotoImage(file="Imagens/image3.gif")  # 3
image5 = image5.subsample(1, 1)
labelimage5 = Label(bg='black', image=image5)

image6 = PhotoImage(file="Imagens/image4.gif")  # 4
image6 = image6.subsample(1, 1)
labelimage6 = Label(bg='black', image=image6)

imageover = PhotoImage(file="Imagens/gameover.gif")  # 11
imageover = imageover.subsample(1, 1)
labelimageover = Label(bg='black', image=imageover)

imageganhou = PhotoImage(file="Imagens/ganhou.gif")  # 11
imageganhou = imageganhou.subsample(1, 1)
labelimageganhou = Label(bg='black', image=imageganhou)


#   FRAMES:

frame1 = Frame(janela)  # Botões de iniciar jogo e como jogar.
frame2 = Frame(janela)  # Botões das disciplinas
framep = Frame(janela)  # Label de perguntas.
frameb = Frame(janela)  # botões das alternativas.
framer = Frame(janela)  # reiniciar
framej = Frame(janela)
frame1.pack(side=BOTTOM, pady='200')  # Botões empacotados de "iniciar" e "como jogar".
framep.pack(pady='90')
frameb.pack(side=BOTTOM, pady='100', padx='1')


#   FUNÇÕES:


def pergunta0():
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    pergunta00.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A.pack()
    B.pack()
    C.pack()
    D.pack()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimage.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    framer.pack_forget()
    frame1.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta1():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta01.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A1.pack()
    B1.pack()
    C1.pack()
    D1.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta00.pack_forget()
    A.pack_forget()
    B.pack_forget()
    C.pack_forget()
    D.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta2():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta02.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A2.pack()
    B2.pack()
    C2.pack()
    D2.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta01.pack_forget()
    A1.pack_forget()
    B1.pack_forget()
    C1.pack_forget()
    D1.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta3():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage6.place_forget()
    labelimage5.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta03.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A3.pack()
    B3.pack()
    C3.pack()
    D3.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta02.pack_forget()
    A2.pack_forget()
    B2.pack_forget()
    C2.pack_forget()
    D2.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta4():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimageover.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    pergunta04.pack()
    A4.pack()
    B4.pack()
    C4.pack()
    D4.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta03.pack_forget()
    A3.pack_forget()
    B3.pack_forget()
    C3.pack_forget()
    D3.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta5():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta05.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A5.pack()
    B5.pack()
    C5.pack()
    D5.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta04.pack_forget()
    A4.pack_forget()
    B4.pack_forget()
    C4.pack_forget()
    D4.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta6():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta06.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A6.pack()
    B6.pack()
    C6.pack()
    D6.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta05.pack_forget()
    A5.pack_forget()
    B5.pack_forget()
    C5.pack_forget()
    D5.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta7():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta07.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A7.pack()
    B7.pack()
    C7.pack()
    D7.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta06.pack_forget()
    A6.pack_forget()
    B6.pack_forget()
    C6.pack_forget()
    D6.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta8():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta08.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A8.pack()
    B8.pack()
    C8.pack()
    D8.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta07.pack_forget()
    A7.pack_forget()
    B7.pack_forget()
    C7.pack_forget()
    D7.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta9():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta09.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A9.pack()
    B9.pack()
    C9.pack()
    D9.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta08.pack_forget()
    A8.pack_forget()
    B8.pack_forget()
    C8.pack_forget()
    D8.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta10():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta010.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A10.pack()
    B10.pack()
    C10.pack()
    D10.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta09.pack_forget()
    A9.pack_forget()
    B9.pack_forget()
    C9.pack_forget()
    D9.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta11():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta011.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A11.pack()
    B11.pack()
    C11.pack()
    D11.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta010.pack_forget()
    A10.pack_forget()
    B10.pack_forget()
    C10.pack_forget()
    D10.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta12():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage5.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage6.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta012.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A12.pack()
    B12.pack()
    C12.pack()
    D12.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta011.pack_forget()
    A11.pack_forget()
    B11.pack_forget()
    C11.pack_forget()
    D11.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta13():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage5.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage6.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta013.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A13.pack()
    B13.pack()
    C13.pack()
    D13.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta012.pack_forget()
    A12.pack_forget()
    B12.pack_forget()
    C12.pack_forget()
    D12.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta14():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage6.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    reiniciar.pack_forget()
    pergunta014.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A14.pack()
    B14.pack()
    C14.pack()
    D14.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta013.pack_forget()
    A13.pack_forget()
    B13.pack_forget()
    C13.pack_forget()
    D13.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def pergunta15():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage6.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta015.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='140', padx='1')
    A15.pack()
    B15.pack()
    C15.pack()
    D15.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta014.pack_forget()
    A14.pack_forget()
    B14.pack_forget()
    C14.pack_forget()
    D14.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def gameover():
    pygame.mixer.music.load('Audio/errou.mp3')
    pygame.mixer.music.play()
    labelimageover.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    reiniciar.pack()
    framer.pack(side=BOTTOM, pady='250', padx='1')
    reiniciar2.pack_forget()
    framep.pack_forget()
    frameb.pack_forget()
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimageganhou.place_forget()
    pergunta00.pack_forget()
    pergunta01.pack_forget()
    pergunta02.pack_forget()
    pergunta03.pack_forget()
    pergunta04.pack_forget()
    pergunta05.pack_forget()
    pergunta06.pack_forget()
    pergunta07.pack_forget()
    pergunta08.pack_forget()
    pergunta09.pack_forget()
    pergunta010.pack_forget()
    pergunta011.pack_forget()
    pergunta012.pack_forget()
    pergunta013.pack_forget()
    pergunta014.pack_forget()
    pergunta015.pack_forget()
    A.pack_forget()
    B.pack_forget()
    C.pack_forget()
    D.pack_forget()
    A1.pack_forget()
    B1.pack_forget()
    C1.pack_forget()
    D1.pack_forget()
    A2.pack_forget()
    B2.pack_forget()
    C2.pack_forget()
    D2.pack_forget()
    A3.pack_forget()
    B3.pack_forget()
    C3.pack_forget()
    D3.pack_forget()
    A4.pack_forget()
    B4.pack_forget()
    C4.pack_forget()
    D4.pack_forget()
    A5.pack_forget()
    B5.pack_forget()
    C5.pack_forget()
    D5.pack_forget()
    A6.pack_forget()
    B6.pack_forget()
    C6.pack_forget()
    D6.pack_forget()
    A7.pack_forget()
    B7.pack_forget()
    C7.pack_forget()
    D7.pack_forget()
    A8.pack_forget()
    B8.pack_forget()
    C8.pack_forget()
    D8.pack_forget()
    A9.pack_forget()
    B9.pack_forget()
    C9.pack_forget()
    D9.pack_forget()
    A10.pack_forget()
    B10.pack_forget()
    C10.pack_forget()
    D10.pack_forget()
    A11.pack_forget()
    B11.pack_forget()
    C11.pack_forget()
    D11.pack_forget()
    A12.pack_forget()
    B12.pack_forget()
    C12.pack_forget()
    D12.pack_forget()
    A13.pack_forget()
    B13.pack_forget()
    C13.pack_forget()
    D13.pack_forget()
    A14.pack_forget()
    B14.pack_forget()
    C14.pack_forget()
    D14.pack_forget()
    A15.pack_forget()
    B15.pack_forget()
    C15.pack_forget()
    D15.pack_forget()


def certo():
    pygame.mixer.music.load('Audio/aplausos.mp3')
    pygame.mixer.music.play()
    labelimageganhou.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    reiniciar2.pack()
    framer.pack(side=BOTTOM, pady='250', padx='1')
    labelimage.place_forget()
    labelimage2.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()

    labelimageover.place_forget()
    frameb.pack_forget()
    framep.pack_forget()


def comojogar0():
    iniciarjogo.pack()
    comojogar.pack_forget()
    labelimage2.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    frameb.pack_forget()
    music()


def music():
    pygame.mixer.music.load('Audio/music.mp3')
    pygame.mixer.music.play()


#   WIDJETS:

iniciarjogo = Button(frame1, text='Iniciar Jogo', font='80', width='35', bg='black', fg='white', command=pergunta0)
iniciarjogo.pack(side=LEFT)
comojogar = Button(frame1, text='Como Jogar', font='80', width='35', bg='black', fg='white', command=comojogar0)
comojogar.pack(side=RIGHT)
reiniciar = Button(framer, text='Tentar Novamente', font='80', width='0', bg='green', fg='white', command=pergunta0)
reiniciar2 = Button(framer, text='Jogar novamente', font='80', width='0', bg='green', fg='white', command=pergunta0)

pergunta00 = Label(framep, text='Como são chamadas as doenças causadas por fungos?', font=font, bg='white', fg='black')
A = Button(frameb, text='Micelos', font='80', width='35', bg='black', fg='white', command=gameover)
B = Button(frameb, text='Micose', font='80', width='35', bg='black', fg='white', command=pergunta1)
C = Button(frameb, text='Globo', font='80', width='35', bg='black', fg='white', command=gameover)
D = Button(frameb, text='Hifas', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta01 = Label(framep, text='Sobre os fungos, diga:', font=font, bg='white', fg='black')
A1 = Button(frameb, text='Heterótrofos', font='80', width='35', bg='black', fg='white', command=pergunta2)
B1 = Button(frameb, text='Procariontes', font='80', width='35', bg='black', fg='white', command=gameover)
C1 = Button(frameb, text='Não possue parede celular', font='80', width='35', bg='black', fg='white', command=gameover)
D1 = Button(frameb, text='Nenhuma', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta02 = Label(framep, text='O termo profilaxia dentre as noções de parasitismo se refere a:', font=font,
                   bg='white', fg='black')
A2 = Button(frameb, text='Organismo que transmite o parasita', font='80', width='35', bg='black', fg='white',
            command=gameover)
B2 = Button(frameb, text='Prevenção', font='80', width='35', bg='black', fg='white', command=pergunta3)
C2 = Button(frameb, text='Abrigar a fase larvária do parasita', font='80', width='35', bg='black', fg='white',
            command=gameover)
D2 = Button(frameb, text='Efetuar o ciclo em um hospedeiro ', font='80', width='35', bg='black', fg='white',
            command=gameover)

pergunta03 = Label(framep, text='Qual dessas doenças NÃO é causada por protozoários?', font=font, bg='white',
                   fg='black')
A3 = Button(frameb, text='Malária', font='80', width='35', bg='black', fg='white', command=pergunta4)
B3 = Button(frameb, text='Amebíase', font='80', width='35', bg='black', fg='white', command=gameover)
C3 = Button(frameb, text='Giardíase', font='80', width='35', bg='black', fg='white', command=gameover)
D3 = Button(frameb, text='Candidíase', font='80', width='35', bg='black', fg='white', command=pergunta4)

pergunta04 = Label(framep, text='Sobre a estrutura bacteriana, qual NÃO está correta?', font=font, bg='white',
                   fg='black')
A4 = Button(frameb, text='Ribossomos', font='80', width='35', bg='black', fg='white', command=gameover)
B4 = Button(frameb, text='Nucleoíde', font='80', width='35', bg='black', fg='white', command=gameover)
C4 = Button(frameb, text='Fímbrias', font='80', width='35', bg='black', fg='white', command=gameover)
D4 = Button(frameb, text='Complexo de Golgi', font='80', width='35', bg='black', fg='white', command=pergunta5)

pergunta05 = Label(framep, text=' A reprodução bactéria pode ser feita:', font=font, bg='white', fg='black')
A5 = Button(frameb, text='Assexuada por conjunção, transformação e transdução.', font='80', width='45', bg='black',
            fg='white', command=gameover)
B5 = Button(frameb, text='Sexuada por conjunção, absorção e transformação', font='80', width='45', bg='black',
            fg='white', command=gameover)
C5 = Button(frameb, text='Assexuada por conjunção, absorção e transformação', font='80', width='45', bg='black',
            fg='white', command=gameover)
D5 = Button(frameb, text='Sexuada por conjunção, transformação e transdução', font='80', width='45', bg='black',
            fg='white', command=pergunta6)

pergunta06 = Label(framep, text='Qual dessas doenças não é causada por bactérias?', font=font, bg='white', fg='black')
A6 = Button(frameb, text='Tétano', font='80', width='35', bg='black', fg='white', command=gameover)
B6 = Button(frameb, text='Gonorréia', font='80', width='35', bg='black', fg='white', command=gameover)
C6 = Button(frameb, text='Malária', font='80', width='35', bg='black', fg='white', command=pergunta7)
D6 = Button(frameb, text='Meningite', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta07 = Label(framep, text='Em relação ao protozoários ameboides é incorreto afirmar:', font=font, bg='white',
                   fg='black')
A7 = Button(frameb, text='São em forma de ameba', font='80', width='35', bg='black', fg='white', command=gameover)
B7 = Button(frameb, text='Locomovem-se através de pseudópodos ', font='80', width='35', bg='black', fg='white',
            command=gameover)
C7 = Button(frameb, text='São úteis para captura de alimento', font='80', width='35', bg='black', fg='white',
            command=gameover)
D7 = Button(frameb, text='São protista e tem vida livre.', font='80', width='35', bg='black', fg='white',
            command=pergunta8)

pergunta08 = Label(framep, text='Como se dá nome da reprodução assexuada das bactérias?', font=font, bg='white',
                   fg='black')
A8 = Button(frameb, text='Bipartição', font='80', width='35', bg='black', fg='white', command=pergunta9)
B8 = Button(frameb, text='Profago', font='80', width='35', bg='black', fg='white', command=gameover)
C8 = Button(frameb, text='Transdução', font='80', width='35', bg='black', fg='white', command=gameover)
D8 = Button(frameb, text='Conjunção', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta09 = Label(framep, text='A morfologia de uma bactéria Cilíndrica é representada por:', font=font,
                   bg='white', fg='black')
A9 = Button(frameb, text='Vibriões', font='80', width='35', bg='black', fg='white', command=gameover)
B9 = Button(frameb, text='Bacilos', font='80', width='35', bg='black', fg='white', command=pergunta10)
C9 = Button(frameb, text='Estreptococos', font='80', width='35', bg='black', fg='white', command=gameover)
D9 = Button(frameb, text='Nenhuma das alternativas', font='80', width='35', bg='black', fg='white',
            command=gameover)

pergunta010 = Label(framep, text='Todos os endoparasitas tem em especial...', font=font, bg='white', fg='black')
A10 = Button(frameb, text='Não apresentam estruturas especiais para deslocamento', font='80', width='45', bg='black',
             fg='white', command=pergunta11)
B10 = Button(frameb, text='Apresentam e utilizam cílios para locomoção', font='80', width='45', bg='black', fg='white',
             command=gameover)
C10 = Button(frameb, text='Utilizam flagelo para locomoção e captura de alimentos ', font='80', width='45', bg='black',
             fg='white', command=gameover)
D10 = Button(frameb, text='Nenhuma', font='80', width='45', bg='black', fg='white', command=gameover)

pergunta011 = Label(framep, text='Como é chamada a micose que geralmente é inofensiva no seu ambiente natural?',
                    font=font, bg='white', fg='black')
A11 = Button(frameb, text='Sistêmica', font='80', width='45', bg='black',
             fg='white', command=gameover)
B11 = Button(frameb, text='Subcutânea', font='80', width='45', bg='black', fg='white',
             command=gameover)
C11 = Button(frameb, text='Oportunista', font='80', width='45', bg='black',
             fg='white', command=pergunta12)
D11 = Button(frameb, text='Superficial', font='80', width='45', bg='black', fg='white', command=gameover)

pergunta012 = Label(framep, text='Existe duas formas do micelos, quais são elas?', font=font, bg='white', fg='black')
A12 = Button(frameb, text='Reprodutivos', font='80', width='45', bg='black',
             fg='white', command=gameover)
B12 = Button(frameb, text='Vegetativos', font='80', width='45', bg='black', fg='white',
             command=gameover)
C12 = Button(frameb, text='Septadas', font='80', width='45', bg='black',
             fg='white', command=gameover)
D12 = Button(frameb, text='Reprodutivos e Vegetativos', font='80', width='45', bg='black', fg='white', command=pergunta13)

pergunta013 = Label(framep, text='Sobre Helmintos: Esquistossomose e cisticercose são causadas por:', font=font,
                    bg='white', fg='black')
A13 = Button(frameb, text='Platelmintos', font='80', width='45', bg='black',
             fg='white', command=pergunta14)
B13 = Button(frameb, text='Nematelmintos', font='80', width='45', bg='black', fg='white',
             command=gameover)
C13 = Button(frameb, text='Platelmintos e Nematelmintos', font='80', width='45', bg='black',
             fg='white', command=gameover)
D13 = Button(frameb, text='Nenhuma', font='80', width='45', bg='black', fg='white', command=gameover)

pergunta014 = Label(framep, text='Qual dessas doenças é a causadora da coçeira anal, principalmente em crianças? ',
                    font=font, bg='white', fg='black')
A14 = Button(frameb, text='Filarióse', font='80', width='45', bg='black',
             fg='white', command=pergunta15)
B14 = Button(frameb, text='Esquistossomose', font='80', width='45', bg='black', fg='white',
             command=gameover)
C14 = Button(frameb, text='Hidatidose', font='80', width='45', bg='black',
             fg='white', command=gameover)
D14 = Button(frameb, text='Oxiurose', font='80', width='45', bg='black', fg='white', command=pergunta15)

pergunta015 = Label(framep, text='A ascaridíase é uma doença causada por:', font=font, bg='white', fg='black')
A15 = Button(frameb, text='Fungos', font='80', width='45', bg='black',
             fg='white', command=certo)
B15 = Button(frameb, text='Nematelmintos', font='80', width='45', bg='black', fg='white',
             command=certo)
C15 = Button(frameb, text='Larva migrans', font='80', width='45', bg='black',
             fg='white', command=gameover)
D15 = Button(frameb, text='Nenhuma', font='80', width='45', bg='black', fg='white', command=gameover)

janela.mainloop()
